dist: trusty
sudo: required

language: c

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update --yes
  - sudo apt-get install --yes -f gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

before_script:

script:
  - cmake .
  - make
  - ./h2get firefox.rb www.fastly.com
