dist: trusty

language: c

compiler:
  - gcc

before_install:
  - add-apt-repository ppa:ubuntu-toolchain-r/test
  - apt-get update
  - apt-get install gcc-4.9 g++-4.9

before_script:

script:
  - cmake .
  - make
  - ./h2get firefox.rb www.fastly.com
